/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseStudiesIndexRouteImport } from './routes/case-studies.index'
import { Route as CaseStudiesTasksyncRouteImport } from './routes/case-studies.tasksync'
import { Route as CaseStudiesSportzInteractiveRouteImport } from './routes/case-studies.sportz-interactive'
import { Route as CaseStudiesSaathiPadsRouteImport } from './routes/case-studies.saathi-pads'
import { Route as CaseStudiesIbaCosmeticsRouteImport } from './routes/case-studies.iba-cosmetics'
import { Route as CaseStudiesComdailyRouteImport } from './routes/case-studies.comdaily'
import { Route as CaseStudiesAmazonRouteImport } from './routes/case-studies.amazon'

const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIndexRoute = CaseStudiesIndexRouteImport.update({
  id: '/case-studies/',
  path: '/case-studies/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesTasksyncRoute = CaseStudiesTasksyncRouteImport.update({
  id: '/case-studies/tasksync',
  path: '/case-studies/tasksync',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSportzInteractiveRoute =
  CaseStudiesSportzInteractiveRouteImport.update({
    id: '/case-studies/sportz-interactive',
    path: '/case-studies/sportz-interactive',
    getParentRoute: () => rootRouteImport,
  } as any)
const CaseStudiesSaathiPadsRoute = CaseStudiesSaathiPadsRouteImport.update({
  id: '/case-studies/saathi-pads',
  path: '/case-studies/saathi-pads',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesIbaCosmeticsRoute = CaseStudiesIbaCosmeticsRouteImport.update({
  id: '/case-studies/iba-cosmetics',
  path: '/case-studies/iba-cosmetics',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesComdailyRoute = CaseStudiesComdailyRouteImport.update({
  id: '/case-studies/comdaily',
  path: '/case-studies/comdaily',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesAmazonRoute = CaseStudiesAmazonRouteImport.update({
  id: '/case-studies/amazon',
  path: '/case-studies/amazon',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/resume': typeof ResumeRoute
  '/case-studies/amazon': typeof CaseStudiesAmazonRoute
  '/case-studies/comdaily': typeof CaseStudiesComdailyRoute
  '/case-studies/iba-cosmetics': typeof CaseStudiesIbaCosmeticsRoute
  '/case-studies/saathi-pads': typeof CaseStudiesSaathiPadsRoute
  '/case-studies/sportz-interactive': typeof CaseStudiesSportzInteractiveRoute
  '/case-studies/tasksync': typeof CaseStudiesTasksyncRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/resume': typeof ResumeRoute
  '/case-studies/amazon': typeof CaseStudiesAmazonRoute
  '/case-studies/comdaily': typeof CaseStudiesComdailyRoute
  '/case-studies/iba-cosmetics': typeof CaseStudiesIbaCosmeticsRoute
  '/case-studies/saathi-pads': typeof CaseStudiesSaathiPadsRoute
  '/case-studies/sportz-interactive': typeof CaseStudiesSportzInteractiveRoute
  '/case-studies/tasksync': typeof CaseStudiesTasksyncRoute
  '/case-studies': typeof CaseStudiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/resume': typeof ResumeRoute
  '/case-studies/amazon': typeof CaseStudiesAmazonRoute
  '/case-studies/comdaily': typeof CaseStudiesComdailyRoute
  '/case-studies/iba-cosmetics': typeof CaseStudiesIbaCosmeticsRoute
  '/case-studies/saathi-pads': typeof CaseStudiesSaathiPadsRoute
  '/case-studies/sportz-interactive': typeof CaseStudiesSportzInteractiveRoute
  '/case-studies/tasksync': typeof CaseStudiesTasksyncRoute
  '/case-studies/': typeof CaseStudiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/resume'
    | '/case-studies/amazon'
    | '/case-studies/comdaily'
    | '/case-studies/iba-cosmetics'
    | '/case-studies/saathi-pads'
    | '/case-studies/sportz-interactive'
    | '/case-studies/tasksync'
    | '/case-studies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/resume'
    | '/case-studies/amazon'
    | '/case-studies/comdaily'
    | '/case-studies/iba-cosmetics'
    | '/case-studies/saathi-pads'
    | '/case-studies/sportz-interactive'
    | '/case-studies/tasksync'
    | '/case-studies'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/resume'
    | '/case-studies/amazon'
    | '/case-studies/comdaily'
    | '/case-studies/iba-cosmetics'
    | '/case-studies/saathi-pads'
    | '/case-studies/sportz-interactive'
    | '/case-studies/tasksync'
    | '/case-studies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ResumeRoute: typeof ResumeRoute
  CaseStudiesAmazonRoute: typeof CaseStudiesAmazonRoute
  CaseStudiesComdailyRoute: typeof CaseStudiesComdailyRoute
  CaseStudiesIbaCosmeticsRoute: typeof CaseStudiesIbaCosmeticsRoute
  CaseStudiesSaathiPadsRoute: typeof CaseStudiesSaathiPadsRoute
  CaseStudiesSportzInteractiveRoute: typeof CaseStudiesSportzInteractiveRoute
  CaseStudiesTasksyncRoute: typeof CaseStudiesTasksyncRoute
  CaseStudiesIndexRoute: typeof CaseStudiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/': {
      id: '/case-studies/'
      path: '/case-studies'
      fullPath: '/case-studies/'
      preLoaderRoute: typeof CaseStudiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/tasksync': {
      id: '/case-studies/tasksync'
      path: '/case-studies/tasksync'
      fullPath: '/case-studies/tasksync'
      preLoaderRoute: typeof CaseStudiesTasksyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/sportz-interactive': {
      id: '/case-studies/sportz-interactive'
      path: '/case-studies/sportz-interactive'
      fullPath: '/case-studies/sportz-interactive'
      preLoaderRoute: typeof CaseStudiesSportzInteractiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/saathi-pads': {
      id: '/case-studies/saathi-pads'
      path: '/case-studies/saathi-pads'
      fullPath: '/case-studies/saathi-pads'
      preLoaderRoute: typeof CaseStudiesSaathiPadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/iba-cosmetics': {
      id: '/case-studies/iba-cosmetics'
      path: '/case-studies/iba-cosmetics'
      fullPath: '/case-studies/iba-cosmetics'
      preLoaderRoute: typeof CaseStudiesIbaCosmeticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/comdaily': {
      id: '/case-studies/comdaily'
      path: '/case-studies/comdaily'
      fullPath: '/case-studies/comdaily'
      preLoaderRoute: typeof CaseStudiesComdailyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/amazon': {
      id: '/case-studies/amazon'
      path: '/case-studies/amazon'
      fullPath: '/case-studies/amazon'
      preLoaderRoute: typeof CaseStudiesAmazonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ResumeRoute: ResumeRoute,
  CaseStudiesAmazonRoute: CaseStudiesAmazonRoute,
  CaseStudiesComdailyRoute: CaseStudiesComdailyRoute,
  CaseStudiesIbaCosmeticsRoute: CaseStudiesIbaCosmeticsRoute,
  CaseStudiesSaathiPadsRoute: CaseStudiesSaathiPadsRoute,
  CaseStudiesSportzInteractiveRoute: CaseStudiesSportzInteractiveRoute,
  CaseStudiesTasksyncRoute: CaseStudiesTasksyncRoute,
  CaseStudiesIndexRoute: CaseStudiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
